
USE top_songsdb;
CREATE TABLE Top3000 (
id INTEGER(11) AUTO_INCREMENT NOT NULL, 
artist VARCHAR(100) NOT NULL,
album VARCHAR(100) NOT NULL,
year INTEGER(4) NULL,
globalScore DECIMAL(10,4)NULL,
usaScore DECIMAL(10,4)NULL,
ukScore DECIMAL(10,4)NULL,
euScore DECIMAL(10,4)NULL,
resScore DECIMAL(10,4)NULL,
PRIMARY KEY(id)
);